"""Guided setup for the W3.5 memory lab.

Auto-detects what's already configured, prompts only for missing pieces,
and is safe to re-run (idempotent). Modeled on guild init's flow:
  1. Detect: existing .env, running services, available models
  2. Prompt: only what the user needs to decide
  3. Apply: start Qdrant, init SQLite, write .env
  4. Verify: smoke-test each dependency
  5. Next step: tell the user what to run

Run:
    .venv/bin/python -m src.lab_init
"""
from __future__ import annotations

import json
import os
import shutil
import socket
import subprocess
import sys
from pathlib import Path
from typing import Any
from urllib.error import URLError
from urllib.request import Request, urlopen

# ── ANSI helpers ──────────────────────────────────────────────────────

_GREEN = "\033[32m"
_YELLOW = "\033[33m"
_RED = "\033[31m"
_BLUE = "\033[34m"
_DIM = "\033[2m"
_RESET = "\033[0m"


def ok(msg: str) -> None:
    print(f"{_GREEN}✓{_RESET} {msg}")


def warn(msg: str) -> None:
    print(f"{_YELLOW}⚠{_RESET} {msg}")


def fail(msg: str) -> None:
    print(f"{_RED}✗{_RESET} {msg}")


def step(msg: str) -> None:
    print(f"\n{_BLUE}▸{_RESET} {msg}")


def dim(msg: str) -> str:
    return f"{_DIM}{msg}{_RESET}"


def ask(prompt: str, default: str = "") -> str:
    suffix = f" {dim(f'[{default}]')}" if default else ""
    val = input(f"  {prompt}{suffix}: ").strip()
    return val or default


def confirm(prompt: str, default: bool = True) -> bool:
    d = "Y/n" if default else "y/N"
    val = input(f"  {prompt} [{d}]: ").strip().lower()
    if not val:
        return default
    return val in ("y", "yes")


# ── Detection ─────────────────────────────────────────────────────────

LAB_DIR = Path(__file__).resolve().parent.parent
ENV_FILE = LAB_DIR / ".env"
DATA_DIR = LAB_DIR / "data"


def port_open(host: str, port: int, timeout: float = 1.0) -> bool:
    try:
        with socket.create_connection((host, port), timeout=timeout):
            return True
    except OSError:
        return False


def http_get(url: str, headers: dict[str, str] | None = None,
             timeout: float = 3.0) -> tuple[int, str]:
    req = Request(url, headers=headers or {})
    try:
        with urlopen(req, timeout=timeout) as r:
            return r.status, r.read().decode("utf-8", errors="replace")
    except URLError as e:
        return 0, str(e)
    except Exception as e:                                      # noqa: BLE001
        return 0, str(e)


def read_env() -> dict[str, str]:
    if not ENV_FILE.exists():
        return {}
    out: dict[str, str] = {}
    for line in ENV_FILE.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        out[k.strip()] = v.strip()
    return out


def write_env(env: dict[str, str]) -> None:
    DATA_DIR.mkdir(exist_ok=True)
    lines = [
        "# .env — W3.5 cross-session memory lab",
        "# auto-generated by src/lab_init.py (safe to edit by hand)",
        "",
    ]
    for k, v in env.items():
        lines.append(f"{k}={v}")
    ENV_FILE.write_text("\n".join(lines) + "\n")


# ── Step implementations ──────────────────────────────────────────────

def check_python_env() -> None:
    step("Checking Python environment")
    if sys.version_info < (3, 11):
        fail(f"Python 3.11+ required; you have {sys.version.split()[0]}")
        sys.exit(1)
    ok(f"Python {sys.version.split()[0]}")
    in_venv = (
        hasattr(sys, "real_prefix")
        or (hasattr(sys, "base_prefix") and sys.base_prefix != sys.prefix)
    )
    if not in_venv:
        warn(
            "Not running inside a virtualenv — strongly recommend "
            ".venv/bin/python -m src.lab_init"
        )
    else:
        ok(f"venv active: {sys.prefix}")


def ensure_qdrant() -> None:
    step("Checking Qdrant vector store")
    if port_open("localhost", 6333):
        ok("Qdrant reachable on localhost:6333")
        return
    warn("Qdrant not running on :6333")
    if not shutil.which("docker"):
        fail("docker not installed — install Docker Desktop / OrbStack first")
        sys.exit(1)
    if confirm("Start Qdrant via docker?", default=True):
        result = subprocess.run(
            ["docker", "ps", "-a", "--filter", "name=qdrant",
             "--format", "{{.Names}}"],
            capture_output=True, text=True, check=False,
        )
        existed = "qdrant" in result.stdout
        cmd = (
            ["docker", "start", "qdrant"] if existed
            else ["docker", "run", "-d", "-p", "6333:6333",
                  "--name", "qdrant", "qdrant/qdrant"]
        )
        subprocess.run(cmd, check=False)
        # Wait briefly for it to come up
        import time
        for _ in range(10):
            if port_open("localhost", 6333):
                ok("Qdrant started")
                return
            time.sleep(0.5)
        fail("Qdrant didn't become reachable within 5s — check docker logs")
        sys.exit(1)
    else:
        fail("Qdrant required; aborting")
        sys.exit(1)


def detect_embed_path(env: dict[str, str]) -> tuple[str, str]:
    """Returns (mode, model_id_or_explainer). Mode is 'omlx' or 'local'."""
    step("Detecting embedding backend")
    omlx_base = env.get("OMLX_BASE_URL", "http://localhost:8000/v1")
    omlx_key = env.get("OMLX_API_KEY", "")

    status, body = http_get(
        f"{omlx_base}/models",
        headers={"Authorization": f"Bearer {omlx_key}"} if omlx_key else None,
    )
    if status == 200:
        try:
            data = json.loads(body)
            models = [m.get("id", "") for m in data.get("data", [])]
        except json.JSONDecodeError:
            models = []
        bge = [m for m in models if "bge" in m.lower()]
        if bge:
            ok(f"oMLX serves embedding model(s): {', '.join(bge)}")
            picked = bge[0]
            if len(bge) > 1:
                picked = ask("Pick embed model id", default=bge[0])
            return ("omlx", picked)
        warn("oMLX reachable but no bge-* embedding model registered")
    elif status == 401:
        warn("oMLX returned 401 — auth required (env OMLX_API_KEY may be unset)")
    else:
        warn(f"oMLX not reachable at {omlx_base} ({body[:80]})")

    print(
        f"  {dim('Fallback: load BGE-M3 in-process via sentence-transformers')}"
        f"\n  {dim('(adds ~1 GB resident, MPS-accelerated on Apple Silicon)')}"
    )
    if confirm("Use sentence-transformers fallback?", default=True):
        return ("local", "BAAI/bge-m3")
    fail("No embedding backend selected; aborting")
    sys.exit(1)


def write_env_file(env: dict[str, str], embed_mode: str,
                   embed_model: str) -> dict[str, str]:
    step("Writing .env")
    defaults = {
        "OMLX_BASE_URL": "http://localhost:8000/v1",
        "OMLX_API_KEY": "",
        "MODEL_SONNET": "gemma-4-26B-A4B-it-heretic-4bit",
        "MODEL_HAIKU": "gpt-oss-20b-MXFP4-Q8",
        "QDRANT_URL": "http://localhost:6333",
        "SQLITE_PATH": "data/memory.db",
        "EMBED_MODEL": embed_model,
        "USE_LOCAL_EMBED": "1" if embed_mode == "local" else "0",
    }
    final = {k: env.get(k, v) for k, v in defaults.items()}
    # Allow interactive override of OMLX_API_KEY when unset
    if not final["OMLX_API_KEY"]:
        key = ask("OMLX_API_KEY", default="")
        if key:
            final["OMLX_API_KEY"] = key
    write_env(final)
    ok(f".env written ({len(final)} keys)")
    return final


def init_sqlite() -> None:
    step("Initializing SQLite schema")
    from src import init_db  # noqa: F401  — running the module is the side effect
    ok("SQLite ready (data/memory.db)")


def smoke_test() -> None:
    step("Smoke-testing the memory module")
    try:
        from src.memory import embed, recall
    except Exception as e:                                       # noqa: BLE001
        fail(f"import src.memory failed: {type(e).__name__}: {e}")
        sys.exit(1)
    try:
        v = embed("hello")
        if len(v) != 1024:
            warn(f"embed dim = {len(v)} (expected 1024) — check embedder")
        else:
            ok(f"embed() OK ({len(v)} dims)")
    except Exception as e:                                       # noqa: BLE001
        fail(f"embed() raised: {type(e).__name__}: {e}")
        sys.exit(1)
    try:
        recall("__init_smoke__", "any food I should avoid?")
        ok("recall() OK")
    except Exception as e:                                       # noqa: BLE001
        fail(f"recall() raised: {type(e).__name__}: {e}")
        sys.exit(1)


def print_next_steps() -> None:
    print(f"\n{_GREEN}{'─' * 60}{_RESET}")
    print(f"{_GREEN}✓ Lab ready.{_RESET}\n")
    print("Next:")
    print("  • Run the 3-session demo:")
    print(f"    {_DIM}.venv/bin/python -m src.demo_three_sessions{_RESET}")
    print("  • Open an interactive chat:")
    print(f"    {_DIM}.venv/bin/python -m src.chat --user alice{_RESET}")
    print("  • Run the 15-Q recall benchmark:")
    print(f"    {_DIM}.venv/bin/python -m pytest tests/test_recall.py -v{_RESET}")
    print(f"{_GREEN}{'─' * 60}{_RESET}")


def main() -> None:
    print(f"\n{_BLUE}W3.5 Memory Lab — Guided Setup{_RESET}\n")
    check_python_env()
    ensure_qdrant()
    env = read_env()
    mode, model = detect_embed_path(env)
    env = write_env_file(env, mode, model)
    # Reload env into process so init_db + smoke_test pick up new vars
    for k, v in env.items():
        os.environ[k] = v
    init_sqlite()
    smoke_test()
    print_next_steps()


if __name__ == "__main__":
    main()
